-- {-# OPTIONS_GHC -O0 #-}
module Main (main) where

import qualified FooSpec

import Test.Hspec

main :: IO ()
main = hspec spec

{-# OPAQUE spec #-}
spec :: Spec
spec = do
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
  FooSpec.spec
